import './style.css';
import {escapeHTML as e, filterFindings, summarize} from './view.mjs';
type Finding={id:string;group:string;kind:string;location:string;target:string;confidence:string;evidence:string[];recommendation:string;risk:string;size:number|null};
type InstalledApp={name:string;publisher:string;version:string;installPath:string;source:string;msi:boolean;uninstallCommand:string};
type Report={created:string;apps:InstalledApp[];findings:Finding[];warnings:string[];truncated:boolean;scanOnly:boolean};
type API={Scan():Promise<Report>;CancelScan():Promise<void>;ExportReport():Promise<void>};
declare global {interface Window{go?:{main:{App:API}};runtime?:{EventsOn(event:string,callback:(message:string)=>void):void}}}
let report:Report|null=null,busy=false,error='',notice='',phase='',page='Dashboard',group='',kind='',confidence='',query='',detail='',selected=new Set<string>();
const root=document.querySelector<HTMLDivElement>('#app')!;
const api=()=>window.go?.main.App;
function button(label:string,action:string,disabled=false,css=''){return `<button class="${css}" data-action="${action}" ${disabled?'disabled':''}>${e(label)}</button>`}
function render(){
 const findings=report?.findings??[],groups=[...new Set(findings.map(f=>f.group))],filtered=filterFindings(findings,group,kind,confidence,query),item=findings.find(f=>f.id===detail);
 root.innerHTML=`<aside class="sidebar"><div class="brand"><img src="/icon.svg" alt=""><div>App Cleanup<br>Doctor</div></div><span class="publisher">ALMARFELD</span><nav>${['Dashboard','Scan results','Inventory','Review','History'].map(p=>`<button data-page="${p}" class="${page===p?'active':''}">${p}</button>`).join('')}</nav><div class="milestone">SCAN ONLY<br><span>Development build · 0.1.0<br>Cleanup and Undo disabled</span></div></aside><main><header><div><p class="eyebrow">OFFLINE WINDOWS UTILITY</p><h1>${e(page)}</h1></div><div class="actions">${button(busy?'Scanning…':'Scan Windows','scan',busy,'primary')}${busy?button('Cancel','cancel'):''}${button('Export report','export',!report||busy)}</div></header><div class="safety">Read-only scan. Nothing is changed or selected automatically. Findings are possible leftovers, not proof that an item is safe to remove.</div>${busy?`<div role="status" class="notice">${e(phase||"Starting read-only scan�")}</div>`:""}${error?`<div role="alert" class="error">${e(error)}</div>`:''}${notice?`<div role="status" class="notice">${e(notice)}</div>`:''}
 ${page==='Dashboard'?`<section class="stats"><article><span>Installed application records</span><strong>${report?report.apps.length:'—'}</strong></article><article><span>Possible leftovers</span><strong>${report?findings.length:'—'}</strong></article><article><span>Changes made</span><strong>0</strong></article><article><span>Quarantine</span><strong>Not enabled</strong></article></section><section class="card intro"><h2>Understand what was left behind</h2><p>Scan application inventory, explicit registry references, startup entries, scheduled task targets and service binaries. Review the exact evidence before considering any change.</p><p>Name-only folder matches are withheld. Shared runtimes and protected system locations are excluded.</p>${button('View scan results','results',!report)}<p class="muted">${report?`Last scan: ${e(report.created)}`:'Start a scan to see results from this computer.'}</p></section>`:''}
 ${page==='Scan results'?`<div class="filters"><label>Type<select id="kind"><option value="">All types</option>${['Files','Registry','Startup','Tasks','Service'].map(x=>`<option ${kind===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Confidence<select id="confidence"><option value="">All confidence</option>${['High','Medium','Low'].map(x=>`<option ${confidence===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="search">Search location or group<input id="query" value="${e(query)}" placeholder="Filter results"></label><span>${filtered.length} shown</span></div><div class="results"><section class="groups"><button data-group="" class="${!group?'active':''}">All groups (${findings.length})</button>${groups.map(g=>`<button data-group="${e(g)}" class="${group===g?'active':''}">${e(g)}</button>`).join('')}</section><div class="table-scroll"><table><thead><tr><th>Review</th><th>Type / Group</th><th>Location / Evidence</th><th>Confidence</th><th>Size</th><th>Recommendation</th></tr></thead><tbody>${filtered.map(f=>`<tr><td><input type="checkbox" data-select="${f.id}" ${selected.has(f.id)?'checked':''} aria-label="Add ${e(f.group)} to review"></td><td>${e(f.kind)}<small>${e(f.group)}</small></td><td><button class="text-link" data-detail="${f.id}">${e(f.location)}</button><small>${e(f.evidence[0])}</small></td><td><span class="badge ${f.confidence.toLowerCase()}">${e(f.confidence)}</span></td><td>Not measured</td><td>${e(f.recommendation)}</td></tr>`).join('')}</tbody></table>${!filtered.length?`<div class="empty">${report?'No matching findings. This does not certify the computer as free of leftovers.':'Run a scan first.'}</div>`:''}</div></div>`:''}
 ${page==='Inventory'?`<section class="card"><h2>Installed application inventory</h2><p class="muted">Uninstall records from both user/machine scopes and registry views. Records do not prove that an installation is healthy. Uninstall commands are displayed as data and never executed.</p><div class="table-scroll"><table><thead><tr><th>Application</th><th>Publisher / Version</th><th>Recorded location</th><th>Source</th></tr></thead><tbody>${(report?.apps??[]).map(a=>`<tr><td>${e(a.name)}${a.msi?'<small>Windows Installer record</small>':''}</td><td>${e(a.publisher)}<small>${e(a.version)}</small></td><td>${e(a.installPath||'Not recorded')}<details><summary>Uninstall command (read only)</summary><code>${e(a.uninstallCommand||'Not recorded')}</code></details></td><td>${e(a.source)}</td></tr>`).join('')}</tbody></table></div></section>`:''}
 ${page==='Review'?review(findings):''}
 ${page==='History'?`<section class="card"><h2>No cleanup sessions</h2><p>This milestone cannot change files, registry entries, startup items, tasks or services. It creates no quarantine or rollback records.</p><p>Quarantine, registry backup, restore and cleanup results will be added only after a separately tested safety milestone.</p>${button('Restore session','none',true)} ${button('Empty quarantine','none',true)}</section>`:''}
 ${report?.warnings?.length?`<details class="warnings"><summary>${report.warnings.length} collection warnings${report.truncated?' · scan limits reached':''}</summary><p>Unreadable sources are not evidence of missing files.</p><ul>${report.warnings.map(w=>`<li>${e(w)}</li>`).join('')}</ul></details>`:''}
 <footer>Fully offline · No uploads · No automatic downloads <span>Report exports include local paths. Share them carefully.</span></footer></main>
 ${item?`<dialog open><h2>Finding details</h2><dl><dt>Group / Type</dt><dd>${e(item.group)} / ${e(item.kind)}</dd><dt>Exact location</dt><dd>${e(item.location)}</dd><dt>Referenced executable</dt><dd>${e(item.target)}</dd><dt>Confidence</dt><dd>${e(item.confidence)} — evidence confidence, not removal safety</dd></dl><h3>Why it was detected</h3><ul>${item.evidence.map(x=>`<li>${e(x)}</li>`).join('')}</ul><h3>Risk</h3><p>${e(item.risk)}</p><p>${e(item.recommendation)}</p>${button('Close details','close')}</dialog>`:''}`;
 bind();
}
function review(findings:Finding[]){const s=summarize(findings,selected);return `<section class="card"><h2>Review selection</h2><p>${s.count} items selected for review · ${s.services} services (report only)</p><p>Reclaimable space is not calculated; folder contents were not traversed. No rollback support is available in this milestone.</p><ul>${findings.filter(f=>selected.has(f.id)).map(f=>`<li>${e(f.kind)} — ${e(f.location)}</li>`).join('')}</ul>${button('Clean selected items — disabled','none',true)}<p class="muted">Selection is a review aid. It does not authorize or perform cleanup.</p></section>`}
function bind(){
 root.querySelectorAll<HTMLElement>('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page!;render()});
 root.querySelectorAll<HTMLElement>('[data-group]').forEach(b=>b.onclick=()=>{group=b.dataset.group!;render()});
 root.querySelectorAll<HTMLElement>('[data-detail]').forEach(b=>b.onclick=()=>{detail=b.dataset.detail!;render()});
 root.querySelectorAll<HTMLInputElement>('[data-select]').forEach(b=>b.onchange=()=>{b.checked?selected.add(b.dataset.select!):selected.delete(b.dataset.select!)});
 const k=root.querySelector<HTMLSelectElement>('#kind');if(k)k.onchange=()=>{kind=k.value;render()};const c=root.querySelector<HTMLSelectElement>('#confidence');if(c)c.onchange=()=>{confidence=c.value;render()};const q=root.querySelector<HTMLInputElement>('#query');if(q)q.onchange=()=>{query=q.value;render()};
 root.querySelectorAll<HTMLElement>('[data-action]').forEach(b=>b.onclick=async()=>{const a=b.dataset.action;error='';notice='';if(a==='close'){detail='';render();return}if(a==='results'){page='Scan results';render();return}if(!api()){error='The Windows desktop bridge is unavailable. Run the packaged application to scan.';render();return}try{if(a==='scan'){busy=true;phase='Starting read-only scan�';report=null;selected.clear();group='';detail='';render();report=await api()!.Scan();page='Scan results'}else if(a==='cancel'){await api()!.CancelScan()}else if(a==='export'){await api()!.ExportReport();notice='Report export dialog closed. Existing files are never overwritten.'}}catch(err){error=String(err)}finally{if(a==='scan')busy=false;render()}});
}
render();

window.runtime?.EventsOn("scan:progress", message => { phase=message; if(busy)render(); });
